nelmio_api_doc:
    areas:
        default:
            path_patterns:
                - '^/api'
            host_patterns: []
            name_patterns: []
            security: []
            with_attribute: false
            disable_default_routes: false
            documentation:
                info:
                    title: 'Decameron API'
                    version: '1.0.0'
    documentation:
        info:
            title: 'Decameron API'
            version: '1.0.0'
