<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703050935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ciudad (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE habitacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, codigo VARCHAR(5) NOT NULL, libre BOOLEAN NOT NULL, activo BOOLEAN NOT NULL, hotel_id INT DEFAULT NULL, tipo_habitacion_id INT DEFAULT NULL, acomodacion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F45995BA20332D99 ON habitacion (codigo)');
        $this->addSql('CREATE INDEX IDX_F45995BA3243BB18 ON habitacion (hotel_id)');
        $this->addSql('CREATE INDEX IDX_F45995BAB0BA7A53 ON habitacion (tipo_habitacion_id)');
        $this->addSql('CREATE INDEX IDX_F45995BA43CAD25A ON habitacion (acomodacion_id)');
        $this->addSql('CREATE TABLE hotel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, direccion VARCHAR(100) NOT NULL, nit VARCHAR(100) NOT NULL, numero_habitaciones INT NOT NULL, activo BOOLEAN NOT NULL, ciudad_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED93A909126 ON hotel (nombre)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED95E5F5AF3 ON hotel (nit)');
        $this->addSql('CREATE INDEX IDX_3535ED9E8608214 ON hotel (ciudad_id)');
        $this->addSql('CREATE TABLE reserva (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cliente VARCHAR(200) NOT NULL, numero_documento VARCHAR(30) NOT NULL, edad INT NOT NULL, fecha_reserva TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fecha_ingreso DATE NOT NULL, fecha_salida DATE NOT NULL, hotel_id INT DEFAULT NULL, habitacion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_188D2E3B3243BB18 ON reserva (hotel_id)');
        $this->addSql('CREATE INDEX IDX_188D2E3BB009290D ON reserva (habitacion_id)');
        $this->addSql('CREATE TABLE tipo_acomodacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tipo_habitacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE habitacion ADD CONSTRAINT FK_F45995BA3243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id)');
        $this->addSql('ALTER TABLE habitacion ADD CONSTRAINT FK_F45995BAB0BA7A53 FOREIGN KEY (tipo_habitacion_id) REFERENCES tipo_habitacion (id)');
        $this->addSql('ALTER TABLE habitacion ADD CONSTRAINT FK_F45995BA43CAD25A FOREIGN KEY (acomodacion_id) REFERENCES tipo_acomodacion (id)');
        $this->addSql('ALTER TABLE hotel ADD CONSTRAINT FK_3535ED9E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE reserva ADD CONSTRAINT FK_188D2E3B3243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id)');
        $this->addSql('ALTER TABLE reserva ADD CONSTRAINT FK_188D2E3BB009290D FOREIGN KEY (habitacion_id) REFERENCES habitacion (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE habitacion DROP CONSTRAINT FK_F45995BA3243BB18');
        $this->addSql('ALTER TABLE habitacion DROP CONSTRAINT FK_F45995BAB0BA7A53');
        $this->addSql('ALTER TABLE habitacion DROP CONSTRAINT FK_F45995BA43CAD25A');
        $this->addSql('ALTER TABLE hotel DROP CONSTRAINT FK_3535ED9E8608214');
        $this->addSql('ALTER TABLE reserva DROP CONSTRAINT FK_188D2E3B3243BB18');
        $this->addSql('ALTER TABLE reserva DROP CONSTRAINT FK_188D2E3BB009290D');
        $this->addSql('DROP TABLE ciudad');
        $this->addSql('DROP TABLE habitacion');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('DROP TABLE reserva');
        $this->addSql('DROP TABLE tipo_acomodacion');
        $this->addSql('DROP TABLE tipo_habitacion');
    }
}
